### ISSUE TITLE
Submit to Bioconda

### ISSUE THREAD

**Issue by rpetit3** [aziele/phirbo#1]
Hi @aziele 

Would it be ok if I were to submit this to Bioconda? If ok, I'll need some help from your end.

Cheers,
Robert

**Comment by aziele** [comment]
Hi @rpetit3 

That would be great. I don't have much experience with Bioconda. How can I help?

Best,
Andrzej

**Comment by rpetit3** [comment]
Do you think you could add an option to print the version (`--version`)? After that I'll just need you to create a release, then I think that's all I'll need.

**Comment by aziele** [comment]
Sure, I added the `--version` option and created first release.

**Comment by rpetit3** [comment]
Thank you! I'll get a recipe submitted soon

**Comment by rpetit3** [comment]
The file [LICENSE](https://github.com/aziele/phirbo/blob/main/LICENSE) file is a MIT file but the README says its [GPL3](https://github.com/aziele/phirbo#license).

Which one should it be?

**Comment by aziele** [comment]
I'm sorry. It should be GPL3. I've updated the repo and the release.

**Comment by rpetit3** [comment]
No worries! Thanks for the info, PR submitted: https://github.com/bioconda/bioconda-recipes/pull/26144

**Comment by aziele** [comment]
Thank you for your help. I really appreciate it!

**Comment by rpetit3** [comment]
This is now available from Bioconda (https://bioconda.github.io/recipes/phirbo/README.html). Going to close! Great stuff!
