### ISSUE TITLE
many null in phirbo/datasets/wang2020/virus.json

### ISSUE THREAD

**Issue by Achuan-2** [aziele/phirbo#3]

**Comment by aziele** [comment]
Hi,

For some viruses in the Wang et al. dataset, hosts are not defined at the species level (only at the genus level). This is the reason for many null values in `phirbo/datasets/wang2020/virus.json`.

**Comment by Achuan-2** [comment]
thanks，and can I ask how to search host name to get host accesssion ID in NCBI，NCBI only provide host name in phage info
there should be a script to achieve this

**Comment by aziele** [comment]
Just to be clear: so you have host names and you want to get the IDs of their genomes?

**Comment by Achuan-2** [comment]
yes，for example，the [github](https://github.com/linsalrob/PhageHosts/tree/master/data) of datasets/edwards2016 only provided host_names or host_taxids of phages，I wonder how to link phage and their host with accession number

**Comment by aziele** [comment]
If you use the GitHub repository (https://github.com/linsalrob/PhageHosts/tree/master/data) you will probably need to write a script to link phage accessions to host accession as this information is scattered across several files. It would probably be easier to use virus.json and host.json. However you will still need a few lines of code. Alternatively, I can generate these mappings and attach here (if you want).

**Comment by aziele** [comment]
Here are the mappings between phages' and hosts' accessions:
[edwards2016.txt](https://github.com/aziele/phirbo/files/8206681/edwards2016.txt)
[galiez2017.txt](https://github.com/aziele/phirbo/files/8206683/galiez2017.txt)
[wang2020.txt](https://github.com/aziele/phirbo/files/8206685/wang2020.txt)
.

**Comment by Achuan-2** [comment]
thanks，but in edwards2016.txt a virus will be connected to many hosts，I have a question that how they use these data to train model, does it need a  virus only link to a reference host accession ID.
![image](https://user-images.githubusercontent.com/60436214/157271895-4b85de3c-87f0-42dd-be89-68135ce7b74e.png)

**Comment by aziele** [comment]
Yes, there are many cases in the Edwards2016 and Wang2020 datasets where one virus is linked to multiple host accessions. This is because one host species can be represented by multiple genome assemblies. For example, NC_007946 and NC_008563 (from your screenshot) are different strains of the same host species (Escherichia coli). As for the model training you might want to look at the [Wang et al. 2020](https://academic.oup.com/nargab/article/2/2/lqaa044/5861484?login=true) study.
