### ISSUE TITLE
Provide scripts to generate ranked lists

### ISSUE THREAD

**Issue by LoreVE** [aziele/phirbo#4]
Hi

I would like to try this tool, but I am a bit confused about how to generate the ranked list from BLAST output. Would it be possible to share the scripts to generate these lists (input for PHIRBO)? 

Thanks!

**Comment by aziele** [comment]
Hi,

Sure! You can find these scripts in the [`utils`](https://github.com/aziele/phirbo/tree/main/utils) directory in the main repository. If your database of potential hosts is large, running BLAST for every prokaryotic genome against the database may be time-consuming. You may therefore want to check our latest tool for phage-host predictions: [PHIST](https://academic.oup.com/bioinformatics/article/38/5/1447/6460800). It is fast, easier to run than Phirbo, and its host predictions are just as good.

**Comment by LoreVE** [comment]
It works! Thanks a lot
